# **Data processing**

In [2]:
import pandas as pd
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
import itertools

#  movies_df

In [3]:
# movies_df = pd.read_csv('/content/drive/MyDrive/Colab/miniMovies.csv')
movies_df = pd.read_csv('/Applications/coding for life/semester4/ML/project/MachineLearning/dataset/movies.dat', sep="::", names=["movieId", "title", "genres"])

movies_df

/var/folders/9m/q_st48_96nxbrmf463nr7q580000gn/T/ipykernel_96689/4281932699.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies_df = pd.read_csv('/Applications/coding for life/semester4/ML/project/MachineLearning/dataset/movies.dat', sep="::", names=["movieId", "title", "genres"])

,movieId,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [5]:
movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)
movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)
movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
movies_df['genres'] = movies_df.genres.str.split('|')
moviesWithGenres_df = movies_df.copy()
for index, row in movies_df.iterrows():
    for genre in row['genres']:
        moviesWithGenres_df.at[index, genre] = 1

moviesWithGenres_df = moviesWithGenres_df.fillna(0)
moviesWithGenres_df = moviesWithGenres_df.set_index(moviesWithGenres_df['movieId']).drop(columns = ['movieId', 'genres'])
moviesWithGenres_df

/var/folders/9m/q_st48_96nxbrmf463nr7q580000gn/T/ipykernel_96689/199810438.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')

,title,year,Animation,Children's,Comedy,Adventure,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Sci-Fi,Documentary,War,Musical,Mystery,Film-Noir,Western
movieId,,,,,,,,,,,,,,,,,,,,
1,Toy Story,1995,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Jumanji,1995,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Grumpier Old Men,1995,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Waiting to Exhale,1995,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Father of the Bride Part II,1995,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3948,Meet the Parents,2000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3949,Requiem for a Dream,2000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3950,Tigerland,2000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3951,Two Family House,2000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3952,"Contender, The",2000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
from pathlib import Path  
path = Path('/Applications/coding for life/semester4/ML/project/MachineLearning/dataset/movie.csv')
moviesWithGenres_df.to_csv(path)

In [4]:
movies_df.describe

<bound method NDFrame.describe of       movieId                               title  \
0           1                    Toy Story (1995)
1           2                      Jumanji (1995)
2           3             Grumpier Old Men (1995)
3           4            Waiting to Exhale (1995)
4           5  Father of the Bride Part II (1995)
...       ...                                 ...
3878     3948             Meet the Parents (2000)
3879     3949          Requiem for a Dream (2000)
3880     3950                    Tigerland (2000)
3881     3951             Two Family House (2000)
3882     3952               Contender, The (2000)

                            genres
0      Animation|Children's|Comedy
1     Adventure|Children's|Fantasy
2                   Comedy|Romance
3                     Comedy|Drama
4                           Comedy
...                            ...
3878                        Comedy
3879                         Drama
3880                         Drama
3881                         Drama
3882                Drama|Thriller

[3883 rows x 3 columns]>

# ratings_df

In [91]:
ratings_df = pd.read_csv('/Applications/coding for life/semester4/ML/project/MachineLearning/dataset/ratings.dat', sep = "::", names = ["userId", "movieId", "rating", "timestamp"], dtype = {'userId':'int32', 'movieId':'int32', 'rating':'float16'})
ratings_df

/var/folders/9m/q_st48_96nxbrmf463nr7q580000gn/T/ipykernel_6123/3952722671.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  ratings_df = pd.read_csv('/Applications/coding for life/semester4/ML/project/MachineLearning/dataset/ratings.dat', sep = "::", names = ["userId", "movieId", "rating", "timestamp"], dtype = {'userId':'int32', 'movieId':'int32', 'rating':'float16'})

         userId  movieId  rating  timestamp
0             1     1193     5.0  978300760
1             1      661     3.0  978302109
2             1      914     3.0  978301968
3             1     3408     4.0  978300275
4             1     2355     5.0  978824291
...         ...      ...     ...        ...
1000204    6040     1091     1.0  956716541
1000205    6040     1094     5.0  956704887
1000206    6040      562     5.0  956704746
1000207    6040     1096     4.0  956715648
1000208    6040     1097     4.0  956715569

[1000209 rows x 4 columns]

In [92]:
from sklearn.model_selection import train_test_split
r_train, r_test = train_test_split(ratings_df, test_size=0.1, stratify=ratings_df['userId'])

Item-user matrix on training set

In [93]:
movieId = movies_df['movieId']
userId = ratings_df['userId'].drop_duplicates()
originalRating = np.full([max(movieId), max(userId)], np.nan)


for line in r_train.itertuples():
    originalRating[line[2]-1][line[1]-1] = line[3]

originalRating

array([[ 5., nan, nan, ..., nan, nan,  3.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [94]:
test = np.full([max(movieId), max(userId)], np.nan)


for line in r_test.itertuples():
    test[line[2]-1][line[1]-1] = line[3]

test = (test.T-np.nanmean(test, axis=1)).T
test = np.nan_to_num(test)

/var/folders/9m/q_st48_96nxbrmf463nr7q580000gn/T/ipykernel_6123/1262481991.py:7: RuntimeWarning: Mean of empty slice
  test = (test.T-np.nanmean(test, axis=1)).T

# ***User-User***

Normalize Item-user matrix

In [96]:
# Normalize Item-user matrix
item_user = (originalRating-np.nanmean(originalRating, axis=0))
# item_user

array([[ 0.83333333,         nan,         nan, ...,         nan,
                nan, -0.57980456],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       ...,
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

Get all movies are not watched by each person

In [84]:
# Get all users do not watched movie i
indexNanMovie = [0 for i in range(max(movieId))]
for i in range(max(movieId)):
    indexNanMovie[i] = np.where(np.isnan(item_user[i]))[0]
# indexNanMovie

Get all movies watched by each person

In [85]:
# Get all movies watched by each person
indexRatedMovie = [0 for i in range(max(movieId))]
for i in range(max(movieId)):
    indexRatedMovie[i] = np.where(~np.isnan(item_user[i]))[0]
# indexRatedMovie


Fill nan value in Item-user matrix with 0

In [86]:
# Fill nan value in Item-user matrix with 0
user_user = np.nan_to_num(item_user)
# user_user

Similarity func

In [87]:
# Similarity func
import math
def cos(x,y):
    if x.dot(y)==0:
        return 0
    return x.dot(y)/math.sqrt(np.sum(x**2)*np.sum(y**2))

Calculate Item similiarity matrix

In [ ]:
# Calculate Item similiarity matrix
similiarityUser = np.full([max(userId), max(userId)], np.nan)
for i in range(max(userId)):
    for j in range(i, max(userId)):
        sim = cos(user_user[:,i], user_user[:,j])
        similiarityUser[i][j] = sim
        similiarityUser[j][i] = sim
# similiarityUser

Predict nan rating

In [ ]:
# Predict nan rating
# 13min
movieId = r_test['movieId'].drop_duplicates()
predict = item_user.copy()
for i in movieId-1:
    rate = (item_user[i][~np.isnan(item_user[i])]) # All ratings of movie i
    rateIndex = indexRatedMovie[i] # users watch movie i
    nul = indexNanMovie[i] # users do not watch movie i
    sim = similiarityUser[nul]
    for u in range(len(sim)):
        predict[i][nul[u]] = (sim[u][rateIndex] @ rate / sum(np.abs(sim[u][rateIndex])))
# predict

<ipython-input-103-dad26dcd0b7c>:11: RuntimeWarning: invalid value encountered in double_scalars
  predict[i][nul[u]] = (sim[u][rateIndex] @ rate / sum(np.abs(sim[u][rateIndex])))

Denormalize predict matrix

In [ ]:
# Denormalize predict matrix
predictUser = (predict + np.nanmean(originalRating, axis=0))
predictUser

array([[5.        , 4.18939254, 4.11867492, ..., 4.04086374, 4.192579  ,
        3.        ],
       [4.19930885, 3.39469074, 3.67901036, ..., 4.08498941, 3.52446939,
        3.1151884 ],
       [4.24315039, 3.29040278, 3.72456436, ..., 3.98034733, 3.49907496,
        3.04308105],
       ...,
       [4.64867974, 4.08033102, 4.21207649, ..., 3.9761123 , 4.05201605,
        3.73199369],
       [4.35874658, 3.87051731, 4.20058606, ..., 3.6131324 , 4.1330905 ,
        3.94369635],
       [4.31234151, 3.90204833, 3.93225944, ..., 4.08725065, 4.00562428,
        3.73284389]])

# ***Item-Item***

Normalize Item-user matrix

In [ ]:
# Normalize Item-user matrix
itemRating = (originalRating.T-np.nanmean(originalRating, axis=1)).T
# itemRating

<ipython-input-105-b680567e990b>:2: RuntimeWarning: Mean of empty slice
  itemRating = (originalRating.T-np.nanmean(originalRating, axis=1)).T

Get all movies are not watched by each person

In [ ]:
# Get all movies are not watched by each person
indexNanMovie = [0 for i in range(max(userId))]
for i in range(max(userId)):
    indexNanMovie[i] = np.where(np.isnan(itemRating.T[i]))[0]

Get all movies watched by each person

In [ ]:
# Get all movies watched by each person
indexRatedMovie = [0 for i in range(max(userId))]
for i in range(max(userId)):
    indexRatedMovie[i] = np.where(~np.isnan(itemRating.T[i]))[0]


Fill nan value in Item-user matrix with 0

In [ ]:
# Fill nan value in Item-user matrix with 0
item_item = np.nan_to_num(itemRating)
# item_item

Similarity func

In [ ]:
# Similarity func
import math
def cos(x,y):
    if x.dot(y)==0:
        return 0
    return x.dot(y)/math.sqrt(np.sum(x**2)*np.sum(y**2))

Calculate Item similiarity matrix

In [ ]:
# Calculate Item similiarity matrix
similiarityItem = np.full([max(movieId), max(movieId)], np.nan)
for i in range(max(movieId)):
    for j in range(i, max(movieId)):
        sim = cos(item_item[i], item_item[j])
        similiarityItem[i][j] = sim
        similiarityItem[j][i] = sim
# similiarityItem

Predict nan rating

In [ ]:
# Predict nan rating
predict = itemRating.copy()
userId = r_test['userId'].drop_duplicates()
for u in userId-1:
    # u = 4
    rate = (itemRating.T[u][~np.isnan(itemRating.T[u])]) # All ratings of u
    rateIndex = indexRatedMovie[u]
    nul = indexNanMovie[u] # movies are not watched by u
    sim = similiarityItem[nul]
    for i in range(len(sim)):
        predict[nul[i]][u] = sim[i][rateIndex] @ rate / sum(np.abs(sim[i][rateIndex]))
# predict

<ipython-input-111-caeda86af62d>:11: RuntimeWarning: invalid value encountered in double_scalars
  predict[nul[i]][u] = sim[i][rateIndex] @ rate / sum(np.abs(sim[i][rateIndex]))

Denormalize predict matrix

In [ ]:
# Denormalize predict matrix
predictItem = (predict.T + np.nanmean(originalRating, axis=1)).T
predictItem

<ipython-input-112-3a157c2f4a6c>:2: RuntimeWarning: Mean of empty slice
  predictItem = (predict.T + np.nanmean(originalRating, axis=1)).T

array([[5.        , 4.24420347, 4.16459785, ..., 4.13031551, 4.05114903,
        3.        ],
       [3.52242288, 3.2751101 , 3.55020159, ..., 3.31181737, 3.09070114,
        2.54882193],
       [3.5053254 , 3.20134006, 3.46677123, ..., 2.93068155, 2.92506785,
        2.51308319],
       ...,
       [4.09505966, 3.83051133, 3.97880763, ..., 3.68126393, 3.76338166,
        3.64697705],
       [4.2103717 , 3.82131111, 3.97630687, ..., 3.69543131, 3.90286952,
        3.81273981],
       [4.06087164, 3.82621382, 3.938134  , ..., 4.09872228, 3.81027257,
        3.62612673]])

# **Evaluate accuracy**

In [ ]:
Item_se = 0
User_se = 0
for r in r_test.itertuples():
    if not np.isnan(predictItem[r[2]-1][r[1]-1]):
        Item_se+=(predictItem[r[2]-1][r[1]-1]-r[3])**2
        User_se+=(predictUser[r[2]-1][r[1]-1]-r[3])**2

print("Item_se: ", end="")
print(math.sqrt(Item_se/len(r_test)))
print("User_se: ", end="")
print(math.sqrt(User_se/len(r_test)))

Item_se: 0.8773455769542564
User_se: 0.9021660629719479